name: Pre-commit Cache
description: 'Composite GitHub Action to cache pre-commit environments'
inputs:
  pre_commit_config:
    description: Path to the pre-commit-config.yaml file. Defaults to '.pre-commit-config.yaml'
    required: false
    default: .pre-commit-config.yaml

branding:
  icon: arrow-down-circle
  color: orange

runs:
  using: "composite"
  steps:
    - name: Get Python Version
      id: python
      shell: bash
      run: echo "version=$(python -c 'import sys;print(".".join([str(sys.version_info.major),str(sys.version_info.minor),str(sys.version_info.micro)]))')" >> $GITHUB_OUTPUT

    - name: Cache Pre-Commit
      uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-${{ steps.python.outputs.version }}-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles(inputs.pre_commit_config) }}
        restore-keys: |
            pre-commit-${{ steps.python.outputs.version }}-${{ runner.os }}-${{ runner.arch }}
            pre-commit-${{ steps.python.outputs.version }}-${{ runner.os }}
            pre-commit-${{ steps.python.outputs.version }}
            pre-commit
